// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awxyikflylmdqtpjzfdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3eHlpa2ZseWxtZHF0cGp6ZmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTk5NzAsImV4cCI6MjA3NTE3NTk3MH0.Cf0cp0iBYwnYTj1d3TSsqJKY-fq0GMY2DCvv9bBbYN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});